output_dir = "output/deepseek-v3-5rnd"
max_workers = 4
rounds = 5
fewshot_example_names = ["verina_basic_15", "verina_basic_44"]

code_gen = false
spec_gen = false
proof_gen = true
code_spec_gen = false
code_proof_gen = true
spec_proof_gen = true
code_spec_proof_gen = true

[gen_lm_config]
provider = "local"
model_name = "deepseek-ai/DeepSeek-V3-0324"
api_base = "http://127.0.0.1:1234/v1/"
api_key = "deepseek-v3-0324"

[baseline_config]
name = "baseline"
resume_from_checkpoint = true

[eval_spec_config]
formal_proving = false
unit_test = true
unit_test_proving = false
use_plausible_pass = true
evidence_rel_dir = "./evidence"
use_evidence = false
save_evidence = true
