output_dir = "output/dsprover2-7b-cp-5rnd"
max_workers = 32
rounds = 1
fewshot_example_names = ["verina_basic_15", "verina_basic_44"]

code_gen = false
spec_gen = false
proof_gen = true
code_spec_gen = false
code_proof_gen = false
spec_proof_gen = false
code_spec_proof_gen = false

[gen_lm_config]
provider = "local"
model_name = "deepseek-ai/DeepSeek-Prover-V2-7B"
api_base = "http://localhost:19838/v1/"

[baseline_config]
name = "custom_prompt_baseline"
resume_from_checkpoint = true

[eval_spec_config]
formal_proving = false
unit_test = true
unit_test_proving = false
use_plausible_pass = true
evidence_rel_dir = "./evidence"
use_evidence = false
save_evidence = true
