output_dir = "output/gpt-o4-mini-proof-64"
max_workers = 128
rounds = 1
fewshot_example_names = ["verina_basic_15", "verina_basic_44"]

code_gen = false
spec_gen = false
proof_gen = true
code_spec_gen = false
code_proof_gen = false
spec_proof_gen = false
code_spec_proof_gen = false

[gen_lm_config]
provider = "openai"
model_name = "o4-mini"


[baseline_config]
name = "proof_refinement"
resume_from_checkpoint = true
refinements = 64

[eval_spec_config]
formal_proving = false
unit_test = true
unit_test_proving = false
use_plausible_pass = true
evidence_rel_dir = "./evidence"
use_evidence = false
save_evidence = true
